import React from 'react';
import { Helmet } from 'react-helmet-async';
import { useTranslation } from '../i18n';

interface SEOHeadProps {
  title?: string;
  description?: string;
  path?: string;
  type?: 'website' | 'article' | 'product';
  image?: string;
}

export const SEOHead: React.FC<SEOHeadProps> = ({ 
  title, 
  description, 
  path = '', 
  type = 'website',
  image = '/assets/hero.png'
}) => {
  const { locale, t } = useTranslation();
  
  const siteUrl = 'https://kanji.next-haru.com';
  // Standardized URL for canonical and alternate links
  const url = `${siteUrl}${path}`;
  
  const defaultTitle = t('seo.title') || 'KanjiGen AI — Japanese Kanji Name Generator | Your Identity in Kanji';
  const defaultDescription = t('seo.description') || 'Discover your Japanese Kanji name with AI. Get a personalized Hanko seal, Sengoku-era family lore, and a unique Kamon crest — all crafted by advanced AI.';
  
  const finalTitle = title ? `${title} | KanjiGen AI` : defaultTitle;
  const finalDescription = description || defaultDescription;

  // JSON-LD schema markup for GEO (Generative Engine Optimization)
  // Focusing on English and Artistic Value as per representative's decision
  const websiteSchema = {
    '@context': 'http://schema.org',
    '@type': 'WebSite',
    url: siteUrl,
    name: 'KanjiGen AI',
    alternateName: ['Japan Name Generator', 'Kanji Generator', 'Kamon Designer'],
    description: finalDescription,
    inLanguage: locale,
    potentialAction: {
      '@type': 'SearchAction',
      target: `${siteUrl}/?q={search_term_string}`,
      'query-input': 'required name=search_term_string'
    }
  };

  const softwareSchema = {
    '@context': 'http://schema.org',
    '@type': 'SoftwareApplication',
    name: 'KanjiGen AI',
    operatingSystem: 'Any',
    applicationCategory: 'HealthApplication/DesignApplication',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD'
    },
    aggregateRating: {
      '@type': 'AggregateRating',
      ratingValue: '4.9',
      reviewCount: '1250'
    },
    description: 'AI-Powered Japanese Heritage Artist creating custom Kanji names, traditional Hanko seals, and bespoke Kamon family crests.'
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What makes KanjiGen AI different from other Japanese name generators?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'KanjiGen AI is an artistic heritage tool that doesn\'t just match sounds. It analyzes your personality and name meaning to craft authentic Kanji names, alongside traditional Hanko seals and bespoke Kamon family crests.'
        }
      },
      {
        '@type': 'Question',
        name: 'Are the Kanji names generated by AI culturally accurate?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes, our AI is trained on centuries of Japanese naming conventions and linguistic heritage, ensuring every Kanji name is meaningful, authentic, and respected by native speakers.'
        }
      },
      {
        '@type': 'Question',
        name: 'What is a Kamon family crest and can I get one?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'A Kamon is a traditional Japanese family emblem. KanjiGen AI generates a custom Kamon specifically designed to match the artistic soul of your generated Kanji name.'
        }
      },
      {
        '@type': 'Question',
        name: 'Can I use my generated Kanji name and Hanko seal for personal branding?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Absolutely. Many users use their generated assets for social media avatars, personal logos, and even reference art for tattoos.'
        }
      },
      {
        '@type': 'Question',
        name: 'Is it free to discover my Japanese Kanji name?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'We offer a free preview of multiple Kanji candidates. To unlock the full premium heritage package including high-res Hanko seals and custom Kamon designs, a small one-time fee applies.'
        }
      }
    ]
  };

  const howToSchema = {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Discover Your Japanese Kanji Heritage',
    step: [
      {
        '@type': 'HowToStep',
        name: 'Enter Your Origin Name',
        text: 'Input your birth name and select your spirit archetype and core virtues.'
      },
      {
        '@type': 'HowToStep',
        name: 'Generate Kanji Candidates',
        text: 'Our AI analyzes your spirit to reveal unique Kanji names with deep meanings.'
      },
      {
        '@type': 'HowToStep',
        name: 'Commission Your Artefacts',
        text: 'Unlock your personalized Hanko seal, family lore, and custom Kamon family crest.'
      }
    ]
  };

  const productSchemaJSONLD = {
    '@context': 'http://schema.org',
    '@type': 'Product',
    name: 'KanjiGen AI Heritage Package',
    image: `${siteUrl}${image}`,
    description: finalDescription,
    brand: {
      '@type': 'Brand',
      name: 'KanjiGen AI'
    },
    offers: {
      '@type': 'Offer',
      url: siteUrl,
      priceCurrency: 'USD',
      price: '4.99',
      availability: 'http://schema.org/InStock',
      seller: {
        '@type': 'Organization',
        name: 'Next-Haru Inc.'
       }
    }
  };

  return (
    <Helmet>
      {/* Standard Meta Tags */}
      <title>{finalTitle}</title>
      <meta name="description" content={finalDescription} />
      <link rel="canonical" href={url} />
      
      {/* i18n hreflang for multi-language support */}
      <link rel="alternate" hrefLang="en" href={`${siteUrl}${path}`} />
      <link rel="alternate" hrefLang="ko" href={`${siteUrl}${path}?lang=ko`} />
      <link rel="alternate" hrefLang="ja" href={`${siteUrl}${path}?lang=ja`} />
      <link rel="alternate" hrefLang="x-default" href={`${siteUrl}${path}`} />

      {/* Open Graph / Facebook */}
      <meta property="og:type" content={type} />
      <meta property="og:url" content={url} />
      <meta property="og:title" content={finalTitle} />
      <meta property="og:description" content={finalDescription} />
      <meta property="og:image" content={`${siteUrl}${image}`} />
      <meta property="og:locale" content={locale === 'ko' ? 'ko_KR' : locale === 'ja' ? 'ja_JP' : 'en_US'} />

      {/* Twitter */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:url" content={url} />
      <meta name="twitter:title" content={finalTitle} />
      <meta name="twitter:description" content={finalDescription} />
      <meta name="twitter:image" content={`${siteUrl}${image}`} />

      {/* Structured Data (JSON-LD) for GEO */}
      <script type="application/ld+json">{JSON.stringify(websiteSchema)}</script>
      <script type="application/ld+json">{JSON.stringify(softwareSchema)}</script>
      <script type="application/ld+json">{JSON.stringify(faqSchema)}</script>
      <script type="application/ld+json">{JSON.stringify(howToSchema)}</script>
      <script type="application/ld+json">{JSON.stringify(productSchemaJSONLD)}</script>
    </Helmet>
  );
};
