import React from 'react';
import { LegalLayout } from './LegalLayout';
import { useTranslation } from '../../i18n';

export const RefundPolicy: React.FC = () => {
  const { locale, t } = useTranslation();

  const renderContent = () => {
    if (locale === 'ko') {
      return (
        <>
          <section>
            <h2 className="text-xl font-bold text-white mb-3 text-gold">1. 디지털 상품 정책</h2>
            <p>KanjiGen AI의 모든 구매 항목은 고객 맞춤형으로 1회성 생성되는 디지털 상품(이미지, 텍스트, 아카이브) 형태이므로, 즉시 제공이 완료된 후에는 원칙적으로 환불이 불가능합니다.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-white mb-3 text-gold">2. 예외적 환불 규정</h2>
            <p className="mb-2">단, 다음의 엄격한 조건에 해당하는 경우에 한하여 예외적으로 환불을 도와드립니다:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>시스템 오류로 인해 디지털 자산이 정상적으로 전송되지 않은 경우.</li>
              <li>기술적 결함으로 인해 결제가 중복으로 발생한 경우.</li>
              <li>고객 본인의 승인 없이 이루어진 명백한 사기성 도용 결제인 경우.</li>
            </ul>
          </section>
          <section>
            <h2 className="text-xl font-bold text-white mb-3 text-gold">3. AI 결과물의 편차 (단순 변심)</h2>
            <p>이름과 텍스트는 AI가 창의적으로 생성하는 결과물이므로, 미적인 취향, 언어의 미묘한 뉘앙스, 이미지의 디테일 등은 매번 달라질 수 있습니다. 이러한 주관적인 불만족이나 단순 변심으로 인한 환불은 허용되지 않습니다.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-white mb-3 text-gold">4. 환불 요청 방법</h2>
            <p>환불 예외 조건에 해당한다고 판단되시는 경우, 결제 후 7일 이내에 주문 ID와 명확한 사유를 포함하여 <a href="mailto:support@next-haru.com" className="text-gold hover:underline">support@next-haru.com</a> 으로 연락해 주십시오.</p>
          </section>
        </>
      );
    }
    if (locale === 'ja') {
      return (
        <>
          <section>
            <h2 className="text-xl font-bold text-white mb-3 text-gold">1. デジタル製品ポリシー</h2>
            <p>KanjiGen AIでのすべての購入は、カスタム生成されたデジタル商品（画像、テキスト、アーカイブ）の即時提供を伴います。したがって、すべての販売は最終的なものであり、原則として返金はできません。</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-white mb-3 text-gold">2. 返金の例外</h2>
            <p className="mb-2">以下の厳密な条件に該当する場合に限り、例外的に返金を認める場合があります：</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>デジタル資産の配信を妨げるシステム障害。</li>
              <li>技術的なエラーによる重複請求。</li>
              <li>承認されていないことが証明された不正な取引。</li>
            </ul>
          </section>
          <section>
            <h2 className="text-xl font-bold text-white mb-3 text-gold">3. AI生成による変動</h2>
            <p>出力はAIによって生成されるため、芸術的なスタイル、言語的ニュアンス、または画像の詳細における変動は想定されており、創造的なプロセスの一部です。生成された美学に対する主観的な不満は返金の理由にはなりません。</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-white mb-3 text-gold">4. お申し込み方法</h2>
            <p>例外的な返金の対象となると判断された場合は、注文IDと具体的な理由を明記の上、購入から7日以内に <a href="mailto:support@next-haru.com" className="text-gold hover:underline">support@next-haru.com</a> までメールでご連絡ください。</p>
          </section>
        </>
      );
    }
    
    // Default English
    return (
      <>
        <section>
          <h2 className="text-xl font-bold text-white mb-3 text-gold">1. Digital Product Policy</h2>
          <p>All purchases on KanjiGen AI result in the immediate delivery of custom-generated digital goods (images, text, archives). Therefore, all sales are final and generally non-refundable.</p>
        </section>
        <section>
          <h2 className="text-xl font-bold text-white mb-3 text-gold">2. Exceptions for Refund</h2>
          <p className="mb-2">We may grant refunds under the following strict conditions:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>System failure preventing the delivery of your digital assets.</li>
            <li>Duplicate charges occurring through technical error.</li>
            <li>Fraudulent transactions proven to be unauthorized.</li>
          </ul>
        </section>
        <section>
          <h2 className="text-xl font-bold text-white mb-3 text-gold">3. AI Generation Variations</h2>
          <p>Because outputs are generated by AI, variations in artistic style, linguistic nuances, or image details are expected and are part of the creative process. Subjective dissatisfaction with the generated aesthetic is not grounds for a refund.</p>
        </section>
        <section>
          <h2 className="text-xl font-bold text-white mb-3 text-gold">4. How to Request</h2>
          <p>If you believe you qualify for an exceptional refund, please email <a href="mailto:support@next-haru.com" className="text-gold hover:underline">support@next-haru.com</a> within 7 days of purchase, including your Order ID and the exact reason for the request.</p>
        </section>
      </>
    );
  };

  return (
    <LegalLayout title={t('footer.refund')}>
      <p className="text-gold/60 text-sm mb-8">{locale === 'ko' ? '최종 수정일: ' : locale === 'ja' ? '最終更新日: ' : 'Last Updated: '}{new Date().toLocaleDateString()}</p>
      {renderContent()}
    </LegalLayout>
  );
};
